use elative;
select * from sales;

--- Use extract month from date 
select year(date) as years ,month(date) as months,
sum(unit_price) as total_revenue from sales 
group by year(date),month(date)
order by years,months;

--- monthly order volume 
select year(date) as order_years,
		month(date) as order_months,
		count(distinct Transaction_id) as total_orders
from sales group by year(date),month(date)
order by order_years,order_months desc

---Top 5 revenue months 
select top 5
	year(date) as order_year,
	month(date) as order_month,
	sum(unit_price) as total_revenue
from sales 
	Group by year(date),month(date)
	order by order_year,order_month desc

---Find the total revenue generated in each month.
select month(date) as order_month,
	sum(unit_price) as total_revenue
from sales group by month(date);

.---Find the number of unique orders placed each month.
select month(date) as order_month,
	count(distinct transaction_id) as total_orders
	from sales group by month(date) order by order_month desc;


---- Retrieve both monthly revenue and monthly order count together.
select 
		month(date) as order_month,
		sum(unit_price) as monthly_revenue,
		count(distinct transaction_id) as monthly_order
from sales 
	group by month(date) 

---Show the top 5 months with the highest total revenue
select top 5 month(date) as top5_months ,
	sum(unit_price) as total_rev
from sales
	group by month(date) order by top5_months desc


--- Find the total revenue generated by each product
select 
	transaction_id,
	sum(unit_price) as total_rev
from sales 
group by transaction_id
order by total_rev desc


---- Display the top 10 products based on total revenue
select top 10
	transaction_id,
	sum(unit_price) as total_rev
from sales 
group by transaction_id
order by total_rev desc

---- Find which product had the lowest total sales
select top 1
	transaction_id,
	sum(unit_price) as total_rev
from sales 
group by transaction_id
order by total_rev asc

---- Calculate the average order amount for each product
select transaction_id,
	avg(unit_price) as avg_order_amount
from sales
group by transaction_id
order by avg_order_amount desc;

--- Find how many unique products were sold in 2024
select 
	count(distinct transaction_id) as unique_products_2024
from sales
where year(date) =2024

---- Filter for a Specific Year or Period
SELECT 
    month(date) AS months,
    SUM(unit_price) AS total_revenue
FROM sales
WHERE year(date) = 2024
GROUP BY month(date)
ORDER BY months;



